### ISSUE TITLE
Will  you merge 2.0-frozenRowsAndColumns into k0stya-rowspan?

### ISSUE THREAD

**Issue by koty** [GerHobbelt/SlickGrid#1]
I appreciate your works.

If at all possible, will  you merge 2.0-frozenRowsAndColumns-work (or 2.0-frozenRowsAndColumns) into k0stya-rowspan?

I want both of frozen column and row span.

**Comment by GerHobbelt** [comment]
I intend to do so; timeframe is uncertain however. Given the complexity of the mix it's a non-trivial 'merge' ;-)

**Comment by GerHobbelt** [comment]
Update: I'm looking for another solution as the mechanism used in that fork (and many other forks and other grids, e.g. jqGrid) is to render 4 panels instead of 1, which has some severe limitations and drawbacks:
- as the 4 canvases are not one, you get issues similar to "syncing" the header/footer positions when scrolling, ergo a lot of code to ensure all panels share & show the same scroll position; this is particularly annoying in the new system where I introduced lazy canvas rendering to slickgrid.
- row or column "pinning" is a no-go with the 4 panel approach while, at least for me, this is a visually better mechanism than only being able to freeze N columns to the left.
- the 4 panel approach clashes badly with row/colspanning, particularly when rows and/or columns are spanning across the 'freeze' boundary, e.g. when particular rows are spanning the entire width of the grid 

Side note: other grid systems out there, such as jqGrid, also do not handle this scenario well -- it looks like everybody went for the "quick fix" which is 4 panels to simulate frozen rows/columns a la MS Excel "freeze panes". I now call it a "quick fix" as several months of progress and thought have me agree entirely with @mleibman in mleibman/SlickGrid#208: row/column freezing & pinning is way harder to do correctly from but a UX and engineering perspective, than anyone thinks.

One of the preconditions that would give frozen/pinned cols/rows a decent chance to interoperate properly with the other grid features, such as row/col _spanning_ and (dreadful!) _paging_, is to render the entire grid, frozen/pinned elements and everyone else, in a single canvas.

Hence the discussion at mleibman/Slickgrid#208 (and other issues related to that one in the original repo) is very relevant and my conclusion today is that, even though @JLync7's work is fabulous, it is not going to enter this repository for it employs a solution which has insufficient power to counter the costs it brings with it.

---

The issue of introducing freezing/pinning power to SlickGrid will be continued in another issue: GerHobbelt/SlickGrid#4
